### ISSUE TITLE
One billion credits each time landing?

### ISSUE THREAD

**Issue by tukoz** [Darcman99/Adde-Endless-Sky#1]
Hey, have been playing with Adde Endless Sky on both 0.9.10 (Beta, Steam) and Compiled source and it works without a flaw :)
Player receives one billion credits each time landing upon the Adde outfitter. Two questions about that:

1. What's the goal?
2. Can we disable that crazy influx of money?

**Comment by Darcman99** [comment]
The billion credits on landing was largely a placeholder just to allow the player to buy whatever they wanted. I could very well change it to a simple one massive payment that the player has a choice of taking or not.

**Comment by tukoz** [comment]
Thanks. Yes making it a choice would be way better IMHO. For imagine that captain skillfully (or not) harvesting asteroids for days and/or trying hard to board/capture pirate ships for weeks just to buy that new generator/engine/weapon/ship(s). Then he land on that centralized special outfitter and receives one billion at once, like *that*. And either he accepts it (making all his previous efforts useless), or he must quit the game and go open the previous save file to copy/paste his real money in the latest one before buying anything ':-|

PS anyway after installing 'Beccas Endless Expansion' and 'Czartrak's Ship Packt' (that I removed) plugins the Adde outfitters are no longer open but that's a different matter, isn't it.

**Comment by Darcman99** [comment]
Currently in the process of reworking it, it will give the player a choice of whether they take an absurd amount of credits or not (9.22e18, highest possible number the player can have for credits).

As for plugins somehow breaking the cheat area, if you have discord you could explain the issues further on https://discord.gg/MCKsFgj. Alternatively you could open an additional issue further explaining the bug you’ve encountered.

**Comment by Darcman99** [comment]
The money issue is now fixed, you now are given a choice for whether you want the money or not. See [3766e16](https://github.com/Darcman99/Adde-Endless-Sky/commit/c8626d9461c62d39ce577079138b028a61f64663).

**Comment by tukoz** [comment]
Appreciated Darcman. Even though I cannot test for I can't land there -» opening issue now.
