### ISSUE TITLE
Outfitters forbidden upon installing other plugins

### ISSUE THREAD

**Issue by tukoz** [Darcman99/Adde-Endless-Sky#2]
Endless sky 0.9.10 (Steam)
Adde Endless Sky cloned as of 2019-10-05.

Adde outfitters (Vanilla, Plugins, ... and Everything at *Omnis*) were working fine until I installed two more plugins[1], resulting in the former being forbidden now, as well as new "people's outfinders appearing:

![20191006114453_1](https://user-images.githubusercontent.com/2217680/66267427-e0da7c00-e830-11e9-8d89-5501ef50f4fa.jpg)
![20191006114505_1](https://user-images.githubusercontent.com/2217680/66267556-86dab600-e832-11e9-8b8b-2784782022eb.jpg)

To be frank I have absolutely no idea which situation of the two (allowed / forbidden by default) is the rightfully intended :o) Anyway asking tribute to any one but the "People" outfitters I'm answered the dreaded « Don't joke with these things. » When the new one send a hostile ship, after what I can land on their system but there's no outfitter there (Bank and Hire are present).

[1]: These two plugins are 'Beccas Endless Expansion' and 'Czartrak's Ship Packt' (that I removed).

**Comment by Darcman99** [comment]
That is intended, those stations with ship sprites are there for testing ship builds against different combat difficulties. It is unfortunate that I cannot split those stations off into their own government to avoid confusion and to prevent the player from being restricted from the main shipyards and outfitters.

Landing onto those ship stations is not intended but unfortunately there is nothing I can do about that due to the nature of how it is structured.

**Comment by tukoz** [comment]
Thanks. Means no more outfitter coming out of Adde plugin, right? Unless a story was added somewhere to allow getting access to them?
Also that makes *a lot* of stations out there, especially for newcomers. Would one planet and outfitter per 'people' makes sense to you -- if the backend structure allows for it?

**Comment by Darcman99** [comment]
Ideally, the player would reload after battling one of the ships so they would still have access to the shipyards and outfitters.

**Comment by tukoz** [comment]
Darcman I'm a bit lost now. Your plugin advertise a « (...) very cheaty all-content area » but this area has become forbidden without a warning that I could see.

**Comment by Darcman99** [comment]
Which is unintentional, I assure you, but if there is no way to fix it for you now in game, I suggest altering your save file to make them friendly again.

**Comment by tukoz** [comment]
Got that Darcman, also I saw a buch of new && edited lines in Adde code; thanks! Will test ASAP (am in the Free Worlds / Navy fighting rght now).
Edited the title to reflect what happened better.
